### ISSUE TITLE
Batch image metadata edition

### ISSUE THREAD

**Issue by schwarty** [NeuroVault/NeuroVault#290] opened 2015-06-23 09:23 UTC
This probably should be solved in pyneurovault but at the moment it is not possible to batch edit the type of the images in a collection. So as far as I know if you have uploaded 70 z-score maps in a collection you need to enter that one by one. And if you have 20 of those collections.... Of course this would also be the case for any additional information that can be associated with the images (such as tags).

**Comment by chrisfilo** [comment] 2015-06-23 18:36
Duplicate of #171. We really need this!

**Closed by chrisfilo** 2015-06-23 18:36 UTC
Labels: duplicate
